### PR TITLE
Refactor to move functionality from controller to model, and adding source link

### LINKED ISSUE #35: Add link to real source of the lyrics
Would be nice to add a link to the source of the lyrics to be open in the default browser.

The link must have name of the source (Wikia, MusicMatch, etc) and point directly to the lyric on their site.

### PR DESCRIPTION
**Pull request by mrkmndz**
In the course of adding link functionality to resolve #35, it became apparent how fragile the system by which songs were stored and mutated was because of an over reliance on the controller layer.  To fix this I refactored a lot of functionality into an immutable Song object which will make further changes and maintenance safer.

### CODE REVIEW

**Comment by emilioastarita** [comment]
Thanks i will be check better on weekend but I wanted to know something. If I understand  are you searching sequentially on each plugin now ? Before we launched the search on all plugins (using async lib) and we use the result of the first plugin that finished. I don't understand very well why was needed to change the design so much here.

**Comment by mrkmndz** [comment]
The existing implementation is sequential as well.  It uses the async library, but it uses detectSeries which per the documentation "runs only a single async operation at a time." (https://caolan.github.io/async/docs.html#detectSeries).  The existing implementation was an abuse of that method that precluded any surfacing of plugin errors so I decided to explicitize it with a simpler recursive loop.

**Comment by emilioastarita** [comment]
Sorry for the delay. Yes it is sequential. It was parallel but it was changed. You are right. The idea is to change the algorithm easily. But still not sure about this changes. 

Some parts of the refactor makes not sense to me and goes too beyond of the scope of the issue. Usually I have no problem with a major refactor but I'm not seeing any gain here. I like the idea of a new `Song` class with immutable properties but it's like here it's mixed the search strategy inside this class and there is too much parameters passing.

I'm using parts of this pull request to add the functionality of Plugin Source / url. But I'm not fully merging this. If you want add me to google hangout to discuss a major refactor like this.

**Comment by mrkmndz** [comment]
Hey Emilio, I'm free to talk to you tomorrow about this refactor, what email should I add you on hangout on?

**Pull request closed without merging**
