### PR TITLE
Fixing Icon Settings Synchronization and loading error 

### PR DESCRIPTION
**Pull request by mrkmndz**
Fixes issues #25 and #26

### CODE REVIEW

**Comment by mrkmndz** [comment]
#25 was caused by running AlwaysOnTopSetup after the settings were loaded but not necessarily after the app was ready/ the window was created, making this.getWindow() return undefined.

**Comment by mrkmndz** [comment]
Similarly #26 was caused by running createAppIcon before settings were loaded.

**Comment by mrkmndz** [comment]
Therefore the overall issue is a lack of coordinating two asynchronous jobs, so the solution included in this pull request is to share two closure booleans, then conditionally run the render methods only when both jobs have completed.

**Comment by mrkmndz** [comment]
Now also fixes #28

**Review by emilioastarita — CHANGES_REQUESTED** [review]
thanks! could you use `let` to declare the variables? and also would be nice if you refactor that logic on another function outside the constructor

**Comment by mrkmndz** [comment]
Sounds good, done above

**Review by emilioastarita — APPROVED** [review]
Thx!

**Pull request merged**
