### PR TITLE
Add Monochrome icon (to fit theme template) on macos.

### LINKED ISSUE #18: Mac tray icons aren't monochrome
The colorful icon looks weird along the rest of monochrome icons on the menubar.
Something like this would look better imo: captura de pantalla 2016-11-21 17 32 43

### PR DESCRIPTION
**Pull request by Acen**
Closes #18.

Thanks https://github.com/iiiGerardoiii for the icon files themselves.

image

image

### CODE REVIEW

**Review by emilioastarita — APPROVED** [review]

**Comment by iiiGerardoiii** [comment]
Nice!

One thing I noticed is that the icon looks slightly blurry in the screenshots as if it was resized, quite weird since the icon is 16x16px.

**Comment by Acen** [comment]
Yeah, we could increase it. Do we have any full-scale icons to be resized from?

**Comment by iiiGerardoiii** [comment]
I think that even if we had a high-res image of the icon it would still look blurry because resampling.

The icon is 16x16 which is the size of a menubar icon, right? dunno why it looks blurry.

**Comment by Acen** [comment]
It looks like the images themselves are blurry even in github. What's the highest res image we have that could be scaled down?

**Pull request merged**
